version: '2.1'
services:
  service:
    container_name: test.com
    build:
      context: .
    expose:
      - 80/tcp
    networks:
      - godocker
      - local
    volumes:
      - .:/go/src/work
networks:
  godocker:
    external:
      name: fjob_default
  local:
